server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    inetutils:
      ignoredInterfaces:
        - VirtualBox.*
        - Hyper-V.*
        - Npcap.*
        - VMware.*
    gateway:
      routes:
        - id: PRODUIT-SERVICE
          uri: lb://PRODUIT-SERVICE
          predicates:
            - Path=/produit/**
        - id: STOCK-SERVICE
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost